# Generated by Django 5.2.8 on 2025-11-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('Double', 'Double'), ('Bedspacers', 'Bedspacers'), ('Single', 'Single')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.boarder')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('GCash', 'GCash'), ('Cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.boarder')),
            ],
        ),
        migrations.AddField(
            model_name='boarder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='app.room'),
        ),
    ]
