# Generated by Django 5.2.5 on 2025-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Single', 'Single'), ('Double', 'Double')], max_length=20),
        ),
    ]
