# Generated by Django 5.2.5 on 2025-11-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Double', 'Double'), ('Bedspacers', 'Bedspacers'), ('Single', 'Single')], max_length=20),
        ),
    ]
