# Generated by Django 5.2.8 on 2025-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Single', 'Single'), ('Double', 'Double')], max_length=20),
        ),
    ]
