# Generated by Django 5.2.5 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='dormitory',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dormitory',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Double', 'Double'), ('Single', 'Single'), ('Bedspacers', 'Bedspacers')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Dormitory',
        ),
    ]
