# Generated by Django 5.2.8 on 2025-11-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_room_dormitory_remove_staff_dormitory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Double', 'Double'), ('Single', 'Single')], max_length=20),
        ),
    ]
