# Generated by Django 5.2.8 on 2025-11-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_boarder_user_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Cash', 'Cash')], default='PayPal', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Single', 'Single'), ('Double', 'Double')], max_length=20),
        ),
    ]
