# Generated by Django 5.2.8 on 2025-11-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_transaction_id_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Double', 'Double'), ('Single', 'Single')], max_length=20),
        ),
    ]
