# Generated by Django 5.2.8 on 2025-11-22 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarder', to='app.room'),
        ),
    ]
