# Generated by Django 5.2.8 on 2025-11-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_boarder_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='due_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boarder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='app.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedspacers', 'Bedspacers'), ('Double', 'Double')], max_length=20),
        ),
    ]
