# Generated by Django 5.2.8 on 2025-11-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_room_due_date_alter_boarder_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='due_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Bedspacers', 'Bedspacers')], max_length=20),
        ),
    ]
