# Generated by Django 5.2.8 on 2025-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_room_price_alter_room_due_date_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='due_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bedspacers', 'Bedspacers'), ('Double', 'Double'), ('Single', 'Single')], max_length=20),
        ),
    ]
