# Generated by Django 5.2.8 on 2025-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_room_image_alter_room_due_date_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='due_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedspacers', 'Bedspacers'), ('Double', 'Double')], max_length=20),
        ),
    ]
